### ISSUE TITLE
Why reset the repo?

### ISSUE THREAD

**Issue by iamwilhelm** [adrienhaxaire/funfem#1]
I was looking for a FEM lib and haskell, and then I found that you reset the repo. Was there any particular reason for doing so?

**Comment by adrienhaxaire** [comment]
Sorry for the disappointment. I chose to reset it because it was not usable at all, it was just a playground and I didn't want potential users to lose time because of me. What sort of FEM library are you interested in, i.e. what are the features you are looking for?
